pipeline {
    agent any
    options {
        timeout(time: 2, unit: 'MINUTES')
    }
    stages {
        stage('Run tests with Gradle') {
            steps {
                cmd_exec('gradle test')
            }
        }
        stage('Finalize Run') {
            steps{
                cmd_exec('echo "El pipeline termina aca"')
            }
        }
    }
}