pipeline {
    agent any
    options {
        timeout(time: 2, unit: 'MINUTES')
    }
    stages {
        stage('Run tests with Gradle') {
            steps {
                bat label: '', script: 'gradle test'
            }
        }
        stage('Finalize Run') {
            steps{
                bat label: '', script: 'echo "El pipeline termina aca"'
            }
        }
    }
}